sudo: required
language: node_js
node_js:
  - 6
script:
services:
  - docker
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t delta62/oscar-seed .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push delta62/oscar-seed;
    fi
